twist_mux:
  ros__parameters:
    use_stamped: false
    # output_topic: /diff_drive/cmd_vel

    topics:
      navigation:
        topic: /cmd_vel_nav
        timeout: 0.5
        priority: 10

      teleop:
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 20

      collision:
        topic: /cmd_vel_collision
        timeout: 0.2
        priority: 50