twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      collision:  
        topic: /cmd_vel_collision
        timeout: 0.2
        priority: 50